Repository kookmin-sw/capstone-2024-30, pull requests merged in 2024-04, with the labels that each got.

#44 feature: #42-챗봇 UI 및 기본적인 기능 제작
  front/capstone_front/assets/translations/en-US.json
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/chatbot/chatbot.dart
  front/capstone_front/lib/screens/home_screen.dart
Labels: 📝 feature, 📱 FE

#41 Feature/ai/#17 챗봇 대답에 데이터의 출처 추가하기
  ai/.gitignore
  ai/crawler/__pycache__/notice_crawler.cpython-39.pyc
  ai/crawler/clova_ocr.py
  ai/crawler/test_by_sampling.py
  ai/llm/__pycache__/prompt_template.cpython-39.pyc
  ai/llm/llm_rag.py
  ai/llm/prompt.py
  ai/run_chatbot.py
Labels: 📝 feature, 👽️AI

#45 read pdf
  ai/crawler/pdf_reader.py
Labels: 📝 feature, 👽️AI

#46 feat: #12-Dockerize Backend
  back/Dockerfile
  back/docker-compose.yml
Labels: 🔒 BE, 👷 deploy, 🔨 setting

#53 Feature/be/#22 jwt token
  back/build.gradle
  back/docker-compose.yml
  back/dump.rdb
  back/src/main/java/com/example/capstone/CapstoneApplication.java
  back/src/main/java/com/example/capstone/domain/auth/controller/AuthController.java
  back/src/main/java/com/example/capstone/domain/auth/dto/ReissueRequest.java
  back/src/main/java/com/example/capstone/domain/auth/dto/SigninRequest.java
  back/src/main/java/com/example/capstone/domain/auth/dto/SigninResponse.java
  back/src/main/java/com/example/capstone/domain/auth/dto/TokenResponse.java
  back/src/main/java/com/example/capstone/domain/auth/exception/AlreadyEmailExistException.java
  back/src/main/java/com/example/capstone/domain/auth/service/AuthService.java
  back/src/main/java/com/example/capstone/domain/jwt/JwtAuthenticationFilter.java
  back/src/main/java/com/example/capstone/domain/jwt/JwtClaim.java
  back/src/main/java/com/example/capstone/domain/jwt/JwtTokenProvider.java
  back/src/main/java/com/example/capstone/domain/jwt/PrincipalDetails.java
  back/src/main/java/com/example/capstone/domain/jwt/exception/JwtTokenInvalidException.java
  back/src/main/java/com/example/capstone/domain/menu/controller/MenuController.java
  back/src/main/java/com/example/capstone/domain/menu/entity/Menu.java
  back/src/main/java/com/example/capstone/domain/menu/repository/MenuRepository.java
  back/src/main/java/com/example/capstone/domain/menu/service/MenuService.java
  back/src/main/java/com/example/capstone/domain/user/controller/UserController.java
  back/src/main/java/com/example/capstone/domain/user/dto/SigninRequest.java
  back/src/main/java/com/example/capstone/domain/user/dto/SignupRequest.java
  back/src/main/java/com/example/capstone/domain/user/dto/UserProfileUpdateRequest.java
  back/src/main/java/com/example/capstone/domain/user/entity/User.java
  back/src/main/java/com/example/capstone/domain/user/exception/AlreadyEmailExistException.java
  back/src/main/java/com/example/capstone/domain/user/exception/UserNotFoundException.java
  back/src/main/java/com/example/capstone/domain/user/service/LoginService.java
  back/src/main/java/com/example/capstone/domain/user/service/UserService.java
  back/src/main/java/com/example/capstone/domain/user/util/UserMapper.java
  back/src/main/java/com/example/capstone/global/config/RedisConfig.java
  back/src/main/java/com/example/capstone/global/config/SecurityConfig.java
  back/src/main/java/com/example/capstone/global/config/SwaggerConfig.java
  back/src/main/java/com/example/capstone/global/error/ErrorResponse.java
  back/src/main/java/com/example/capstone/global/error/GlobalExceptionHandler.java
  back/src/main/java/com/example/capstone/global/error/JwtAuthenticationEntryPoint.java
  back/src/main/java/com/example/capstone/global/error/exception/EntityNotFoundException.java
  back/src/main/java/com/example/capstone/global/error/exception/ErrorCode.java
  back/src/main/resources/application.properties
Labels: 📝 feature, 🔒 BE, 🔨 setting

#56 Feature/fe/#54 notice screen
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/home_screen.dart
  front/capstone_front/lib/screens/notice/notice_screen.dart
  front/capstone_front/lib/screens/notice/test_notice_data.dart
  front/capstone_front/lib/screens/notice_detail/notice_detail_screen.dart
Labels: 📝 feature, 📱 FE

#58 feature/fe/#57 QnA 스크린 제작, QnA 디테일 스크린 제작
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/home_screen.dart
  front/capstone_front/lib/screens/notice/notice_screen.dart
  front/capstone_front/lib/screens/qna_detail/qna_detail_screen.dart
  front/capstone_front/lib/screens/qna_detail/test_comment_data.dart
  front/capstone_front/lib/screens/qna_list_screen/qna_list_screen.dart
  front/capstone_front/lib/screens/qna_list_screen/question_card.dart
  front/capstone_front/lib/screens/qna_list_screen/test_question_data.dart
Labels: 📝 feature, 📱 FE

#60 Feature/fe/#59 helper screen
  front/capstone_front/assets/images/carrot_profile.png
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/helper/helper_board/helper_board_screen.dart
  front/capstone_front/lib/screens/helper/helper_board/helper_writing_card.dart
  front/capstone_front/lib/screens/helper/helper_board/helper_writing_json.dart
  front/capstone_front/lib/screens/helper/helper_board/helper_writing_screen.dart
  front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_card.dart
  front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_json.dart
  front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_screen.dart
  front/capstone_front/lib/screens/helper/helper_screen.dart
  front/capstone_front/lib/screens/helper/helper_write_screen.dart
  front/capstone_front/lib/screens/home_screen.dart
  front/capstone_front/lib/utils/basic_button.dart
  front/capstone_front/pubspec.yaml
Labels: 📝 feature, 📱 FE

#62 Feature/fe/#57 qna screen
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/notice/notice_detail_screen.dart
  front/capstone_front/lib/screens/notice/notice_screen.dart
  front/capstone_front/lib/screens/qna/qna_detail/qna_detail_screen.dart
  front/capstone_front/lib/screens/qna/qna_detail/test_comment_data.dart
  front/capstone_front/lib/screens/qna/qna_list_screen/qna_list_screen.dart
  front/capstone_front/lib/screens/qna/qna_list_screen/question_card.dart
  front/capstone_front/lib/screens/qna/qna_list_screen/test_question_data.dart
  front/capstone_front/lib/screens/qna/qna_write/qna_write_screen.dart
  front/capstone_front/lib/screens/qna_list_screen/qna_list_screen.dart
  front/capstone_front/lib/utils/basic_button.dart
Labels: 📝 feature, 📱 FE

#64 Feature/fe/#61 faq screen
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/faq/faq_screen.dart
  front/capstone_front/lib/screens/faq/test_faq_data.dart
  front/capstone_front/lib/screens/home_screen.dart
Labels: 📝 feature, 📱 FE

#67 refactor:#66/홈 화면 UI대규모 변경
  front/capstone_front/assets/fonts/ImcreSoojin.ttf
  front/capstone_front/assets/fonts/WAGURI_TTF.ttf
  front/capstone_front/assets/images/koomin.png
  front/capstone_front/assets/translations/en-US.json
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/chatbot/chatbot.dart
  front/capstone_front/lib/screens/home/home_screen.dart
  front/capstone_front/lib/screens/home_screen.dart
  front/capstone_front/lib/screens/main_screen.dart
  front/capstone_front/lib/utils/bubble_painter1.dart
  front/capstone_front/lib/utils/white_box.dart
  front/capstone_front/pubspec.yaml
  front/capstone_front/test/widget_test.dart
Labels: 🔧 refactor, 📱 FE

#65 Feature/be/#36-발음평가 기능
  back/build.gradle
  back/src/main/java/com/example/capstone/domain/speech/WavStream.java
  back/src/main/java/com/example/capstone/domain/speech/controller/SpeechController.java
  back/src/main/java/com/example/capstone/domain/speech/service/SpeechService.java
  back/src/main/java/com/example/capstone/global/config/SecurityConfig.java
  back/src/main/resources/application.properties
Labels: 📝 feature, 🔒 BE

#75 Feature/be/#74 https
  back/Dockerfile
  back/build.gradle
  back/docker-compose.yml
  back/dump.rdb
  back/env.sh
  back/nginx/Dockerfile
  back/nginx/default.conf
  back/src/main/java/com/example/capstone/CapstoneApplication.java
  back/src/main/java/com/example/capstone/domain/announcement/controller/AnnouncementController.java
  back/src/main/java/com/example/capstone/domain/announcement/entity/Announcement.java
  back/src/main/java/com/example/capstone/domain/announcement/entity/AnnouncementFile.java
  back/src/main/java/com/example/capstone/domain/announcement/repository/AnnouncementRepository.java
  back/src/main/java/com/example/capstone/domain/announcement/service/AnnouncementCallerService.java
  back/src/main/java/com/example/capstone/domain/announcement/service/AnnouncementCrawlService.java
  back/src/main/java/com/example/capstone/domain/announcement/service/AnnouncementSearchService.java
  back/src/main/java/com/example/capstone/domain/announcement/service/AnnouncementUrl.java
  back/src/main/java/com/example/capstone/domain/auth/controller/AuthController.java
  back/src/main/java/com/example/capstone/domain/menu/controller/MenuController.java
  back/src/main/java/com/example/capstone/domain/menu/service/MenuService.java
  back/src/main/java/com/example/capstone/domain/speech/WavStream.java
  back/src/main/java/com/example/capstone/domain/speech/controller/SpeechController.java
  back/src/main/java/com/example/capstone/domain/speech/service/SpeechService.java
  back/src/main/java/com/example/capstone/domain/user/controller/UserController.java
  back/src/main/java/com/example/capstone/domain/user/entity/User.java
  back/src/main/java/com/example/capstone/domain/user/service/LoginService.java
  back/src/main/java/com/example/capstone/domain/user/util/UserMapper.java
  back/src/main/java/com/example/capstone/global/config/AsyncConfig.java
  back/src/main/java/com/example/capstone/global/config/SecurityConfig.java
  back/src/main/java/com/example/capstone/global/entity/BaseTimeEntity.java
  back/src/main/java/com/example/capstone/global/error/exception/ErrorCode.java
  back/src/main/resources/application.properties
Labels: 📝 feature, 🔒 BE, 👷 deploy, 🔨 setting

#91 Feature/fe/#54 notice screen
  front/capstone_front/lib/models/notice_response.dart
  front/capstone_front/lib/screens/notice/notice_detail_screen.dart
  front/capstone_front/lib/screens/notice/notice_screen.dart
  front/capstone_front/lib/screens/notice/test_notice_data.dart
  front/capstone_front/lib/services/notice_service.dart
Labels: 📝 feature, 📱 FE

#99 Feature/fe/#92 speech custom
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/lib/screens/signup/singup_password_screen.dart
  front/capstone_front/lib/screens/speech_practice/speech_custom_sentence.dart
  front/capstone_front/lib/screens/speech_practice/speech_practice_card.dart
  front/capstone_front/lib/screens/speech_practice/speech_practice_screen.dart
  front/capstone_front/lib/screens/speech_practice/speech_select_sentence_screen.dart
  front/capstone_front/lib/screens/speech_practice/speech_sentence_card.dart
  front/capstone_front/lib/screens/speech_practice/utils/example_sentences.dart
  front/capstone_front/lib/screens/speech_practice/utils/simple_recorder.dart
  front/capstone_front/lib/services/speech_service.dart
  front/capstone_front/pubspec.yaml
Labels: 📝 feature, 📱 FE

#97 BE: #95 Api 공통 응답으로 리펙토링 + #96 TestContainer를 이용한 테스트 환경 구축
  back/build.gradle
  back/src/main/java/com/example/capstone/domain/announcement/controller/AnnouncementController.java
  back/src/main/java/com/example/capstone/domain/announcement/dto/AnnouncementListResponse.java
  back/src/main/java/com/example/capstone/domain/announcement/dto/AnnouncementListWrapper.java
  back/src/main/java/com/example/capstone/domain/announcement/service/AnnouncementCrawlService.java
  back/src/main/java/com/example/capstone/domain/announcement/service/AnnouncementSearchService.java
  back/src/main/java/com/example/capstone/domain/auth/controller/AuthController.java
  back/src/main/java/com/example/capstone/domain/menu/controller/MenuController.java
  back/src/main/java/com/example/capstone/domain/menu/service/DecodeUnicodeService.java
  back/src/main/java/com/example/capstone/domain/menu/service/MenuCrawlingService.java
  back/src/main/java/com/example/capstone/domain/menu/service/MenuSearchService.java
  back/src/main/java/com/example/capstone/domain/menu/service/MenuUpdateService.java
  back/src/main/java/com/example/capstone/domain/speech/controller/SpeechController.java
  back/src/main/java/com/example/capstone/domain/user/controller/UserController.java
  back/src/main/java/com/example/capstone/domain/user/dto/SigninRequest.java
  back/src/main/java/com/example/capstone/domain/user/dto/SignupRequest.java
  back/src/main/java/com/example/capstone/domain/user/service/LoginService.java
  back/src/main/java/com/example/capstone/global/config/SecurityConfig.java
  back/src/main/java/com/example/capstone/global/dto/ApiResult.java
  back/src/main/java/com/example/capstone/global/dto/ErrorResponse.java
  back/src/main/java/com/example/capstone/global/dto/HmacRequest.java
  back/src/main/java/com/example/capstone/global/error/GlobalExceptionHandler.java
  back/src/main/java/com/example/capstone/global/error/exception/ErrorCode.java
  back/src/test/java/com/example/capstone/BaseIntegrationTest.java
  back/src/test/java/com/example/capstone/CapstoneApplicationTests.java
  back/src/test/java/com/example/capstone/domain/announcement/controller/AnnouncementControllerTest.java
  back/src/test/java/com/example/capstone/domain/user/controller/UserControllerTest.java
  back/src/test/resources/application.properties
Labels: 🔒 BE

#110 Feature: QnA detail 화면 버그 수정 및 댓글 하트 추가, API 구현
  front/capstone_front/lib/screens/faq/faq_screen.dart
  front/capstone_front/lib/screens/qna/qna_detail/qna_detail_screen.dart
  front/capstone_front/lib/screens/qna/qna_list_screen/qna_list_screen.dart
  front/capstone_front/lib/services/qna_service.dart
Labels: 🐛 bug, 📝 feature, 📱 FE

#107 Feature/be/#84 QnA 질문글 및 댓글 게시판 구현 + #87 FAQ 게시판 기능 구현 + #47 S3를 통한 이미지 업로드 및 다운로드 + #80 학식정보 JSON 양식 수정
  back/build.gradle
  back/src/main/java/com/example/capstone/domain/announcement/controller/AnnouncementController.java
  back/src/main/java/com/example/capstone/domain/auth/controller/AuthController.java
  back/src/main/java/com/example/capstone/domain/menu/controller/MenuController.java
  back/src/main/java/com/example/capstone/domain/menu/entity/Menu.java
  back/src/main/java/com/example/capstone/domain/menu/service/MenuSearchService.java
  back/src/main/java/com/example/capstone/domain/qna/controller/AnswerController.java
  back/src/main/java/com/example/capstone/domain/qna/controller/FAQController.java
  back/src/main/java/com/example/capstone/domain/qna/controller/QuestionController.java
  back/src/main/java/com/example/capstone/domain/qna/dto/AnswerListRequest.java
  back/src/main/java/com/example/capstone/domain/qna/dto/AnswerListResponse.java
  back/src/main/java/com/example/capstone/domain/qna/dto/AnswerPostRequest.java
  back/src/main/java/com/example/capstone/domain/qna/dto/AnswerPutRequest.java
  back/src/main/java/com/example/capstone/domain/qna/dto/AnswerResponse.java
  back/src/main/java/com/example/capstone/domain/qna/dto/FAQListRequest.java
  back/src/main/java/com/example/capstone/domain/qna/dto/FAQListResponse.java
  back/src/main/java/com/example/capstone/domain/qna/dto/FAQPostRequest.java
  back/src/main/java/com/example/capstone/domain/qna/dto/FAQPutRequest.java
  back/src/main/java/com/example/capstone/domain/qna/dto/FAQResponse.java
  back/src/main/java/com/example/capstone/domain/qna/dto/QuestionListRequest.java
  back/src/main/java/com/example/capstone/domain/qna/dto/QuestionListResponse.java
  back/src/main/java/com/example/capstone/domain/qna/dto/QuestionPostRequest.java
  back/src/main/java/com/example/capstone/domain/qna/dto/QuestionPutRequest.java
  back/src/main/java/com/example/capstone/domain/qna/dto/QuestionResponse.java
  back/src/main/java/com/example/capstone/domain/qna/entity/Answer.java
  back/src/main/java/com/example/capstone/domain/qna/entity/FAQ.java
  back/src/main/java/com/example/capstone/domain/qna/entity/FAQImage.java
  back/src/main/java/com/example/capstone/domain/qna/entity/Question.java
  back/src/main/java/com/example/capstone/domain/qna/entity/QuestionImage.java
  back/src/main/java/com/example/capstone/domain/qna/repository/AnswerListRepository.java
  back/src/main/java/com/example/capstone/domain/qna/repository/AnswerRepository.java
  back/src/main/java/com/example/capstone/domain/qna/repository/AnswerRepositoryImpl.java
  back/src/main/java/com/example/capstone/domain/qna/repository/FAQImageCustomRepository.java
  back/src/main/java/com/example/capstone/domain/qna/repository/FAQImageRepository.java
  back/src/main/java/com/example/capstone/domain/qna/repository/FAQImageRepositoryImpl.java
  back/src/main/java/com/example/capstone/domain/qna/repository/FAQListRepository.java
  back/src/main/java/com/example/capstone/domain/qna/repository/FAQRepository.java
  back/src/main/java/com/example/capstone/domain/qna/repository/FAQRepositoryImpl.java
  back/src/main/java/com/example/capstone/domain/qna/repository/QuestionImageCustomRepository.java
  back/src/main/java/com/example/capstone/domain/qna/repository/QuestionImageRepository.java
  back/src/main/java/com/example/capstone/domain/qna/repository/QuestionImageRepositoryImpl.java
  back/src/main/java/com/example/capstone/domain/qna/repository/QuestionListRepository.java
  back/src/main/java/com/example/capstone/domain/qna/repository/QuestionRepository.java
  back/src/main/java/com/example/capstone/domain/qna/repository/QuestionRepositoryImpl.java
  back/src/main/java/com/example/capstone/domain/qna/service/AnswerService.java
  back/src/main/java/com/example/capstone/domain/qna/service/FAQService.java
  back/src/main/java/com/example/capstone/domain/qna/service/ImageService.java
  back/src/main/java/com/example/capstone/domain/qna/service/QuestionService.java
  back/src/main/java/com/example/capstone/global/config/S3Config.java
  back/src/main/java/com/example/capstone/global/dto/ApiResult.java
  back/src/main/java/com/example/capstone/global/error/exception/ErrorCode.java
  back/src/main/resources/application.properties
Labels: 📝 feature, 🔧 refactor, 🔒 BE

#113 Feature/ai/#79 chatbot server
  ai/.gitignore
  ai/crawler/pdf_reader.py
  ai/dockerfile
  ai/llm/__pycache__/llm_rag.cpython-312.pyc
  ai/server.py
Labels: 📝 feature, 👽️AI

#112 Fix: 채팅 버그 + 공지사항 버그 수정
  back-chat/back-chat/.idea/back-chat.iml
  back-chat/back-chat/=
  back-chat/back-chat/Dockerfile
  back-chat/back-chat/app/controllers/chats_controller.rb
  back-chat/back-chat/app/controllers/chats_polling_controller.rb
  back-chat/back-chat/config/routes.rb
  back-chat/back-chat/test/controllers/chats_polling_controller_test.rb
  back/Dockerfile
  back/src/main/generated/com/example/capstone/domain/announcement/mapper/AnnouncementMapperImpl.java
  back/src/main/generated/com/example/capstone/domain/user/util/UserMapperImpl.java
  back/src/main/java/com/example/capstone/domain/announcement/controller/AnnouncementController.java
  back/src/main/java/com/example/capstone/domain/announcement/service/AnnouncementCrawlService.java
  back/src/main/java/com/example/capstone/domain/auth/controller/AuthController.java
  back/src/main/java/com/example/capstone/domain/speech/WavStream.java
  back/src/main/java/com/example/capstone/domain/speech/controller/SpeechController.java
  back/src/main/java/com/example/capstone/domain/user/controller/UserController.java
  back/src/main/java/com/example/capstone/domain/user/service/LoginService.java
  back/src/main/resources/application.properties
Labels: 🔒 BE, 🔨 setting
