Repository kookmin-sw/capstone-2024-30, pull requests merged in 2024-05, with the labels that each got.

#121 Refactor/be/#118 fix controller
  back/src/main/java/com/example/capstone/domain/qna/controller/AnswerController.java
  back/src/main/java/com/example/capstone/domain/qna/controller/FAQController.java
  back/src/main/java/com/example/capstone/domain/qna/controller/QuestionController.java
  back/src/main/java/com/example/capstone/domain/speech/controller/SpeechController.java
  back/src/main/java/com/example/capstone/domain/speech/service/SpeechService.java
Labels: 🐛 bug, 🔧 refactor, 🔒 BE

#124 feature: #92/발음 평가 구현
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/lib/models/speech_model.dart
  front/capstone_front/lib/screens/speech_practice/speech_custom_sentence/speech_custom_sentence.dart
  front/capstone_front/lib/screens/speech_practice/speech_practice_screen.dart
  front/capstone_front/lib/screens/speech_practice/utils/audio_player.dart
  front/capstone_front/lib/screens/speech_practice/utils/recorder_screen.dart
  front/capstone_front/lib/services/auth_service.dart
  front/capstone_front/lib/services/speech_service.dart
Labels: 📝 feature, 📱 FE

#133 fix: 채팅에 room polling 추가
  back-chat/app/controllers/chats_controller.rb
  back-chat/app/controllers/chats_polling_controller.rb
  back-chat/config/routes.rb
Labels: 💩 chore, 🔒 BE

#141 Refactor/be/#140 get request
  back/src/main/java/com/example/capstone/domain/help/controller/HelpController.java
  back/src/main/java/com/example/capstone/domain/qna/controller/AnswerController.java
  back/src/main/java/com/example/capstone/domain/qna/controller/FAQController.java
  back/src/main/java/com/example/capstone/domain/qna/controller/QuestionController.java
Labels: 🔧 refactor, 🔒 BE

#147 refactor: #146-answerCount 계산을 위한 SQL문 수정
  back/src/main/java/com/example/capstone/domain/qna/dto/QuestionListResponse.java
  back/src/main/java/com/example/capstone/domain/qna/dto/QuestionSliceResponse.java
  back/src/main/java/com/example/capstone/domain/qna/repository/QuestionRepositoryImpl.java
Labels: 🔧 refactor

#152 refactor: #151-DTO 기반 Fetch Join 문제 해결
  back/src/main/java/com/example/capstone/domain/qna/repository/FAQImageRepositoryImpl.java
  back/src/main/java/com/example/capstone/domain/qna/repository/QuestionImageRepositoryImpl.java
Labels: 🐛 bug, 🔒 BE

#153 refactor: #151-DTO기반 Fetch Join 문제 해결 - Answer
  back/src/main/java/com/example/capstone/domain/qna/repository/AnswerRepositoryImpl.java
Labels: 🐛 bug, 🔒 BE

#155 Feature/fe/#138 chatbot api
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/lib/screens/chatbot/chatbot.dart
  front/capstone_front/lib/services/chatbot_service.dart
  front/capstone_front/lib/utils/bubble_painter_left.dart
  front/capstone_front/lib/utils/bubble_painter_right.dart
Labels: 📝 feature, 📱 FE

#145 Feature/ai/#144 챗봇 Deepl 적용
  ai/deepl_test.py
  ai/llm/__pycache__/llm_rag.cpython-39.pyc
  ai/llm/deepl_translator.py
  ai/llm/llm_rag.py
  ai/llm/prompt.py
  ai/requirements.txt
  ai/run_chatbot.py
  ai/server.py
  ai/vectordb/__pycache__/vector_db.cpython-39.pyc
Labels: 📱 FE, 👽️AI

#156 [FE] QnA 게시판 관련 기능 구현
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/models/answer_model.dart
  front/capstone_front/lib/models/answer_response.dart
  front/capstone_front/lib/models/qna_post_model.dart
  front/capstone_front/lib/screens/qna/qna_detail/qna_detail_screen.dart
  front/capstone_front/lib/screens/qna/qna_list_screen/qna_list_screen.dart
  front/capstone_front/lib/screens/qna/qna_list_screen/question_card.dart
  front/capstone_front/lib/screens/qna/qna_write/qna_write_screen.dart
  front/capstone_front/lib/services/auth_service.dart
  front/capstone_front/lib/services/helper_service.dart
  front/capstone_front/lib/services/qna_service.dart
Labels: 📝 feature, 📱 FE

#160 fix: secret값들 변경
  .github/workflows/deploy.yml
Labels: 💩 chore, 🔒 BE

#161 feat: #137-qna 디테일 위로 끌어당겨 새로고침, 하단 자동 스크롤 문제 해결
  front/capstone_front/lib/screens/qna/qna_detail/qna_detail_screen.dart
  front/capstone_front/lib/screens/qna/qna_list_screen/qna_list_screen.dart
Labels: 🐛 bug, 📝 feature, 📱 FE

#162 fix: api 문서 접근 가능하게 변경
  .github/workflows/deploy.yml
  back-gateway/src/main/java/com/gateway/backgateway/config/GatewayConfig.java
  back/nginx/Dockerfile
  back/nginx/default.conf.template
Labels: 🐛 bug, 💩 chore, 🔒 BE

#165 Refactor/be/#163 UUID 자료형 String 변경 및 수정 요청 Endpoint에서 UUID 확인 과정 추가
  back/src/main/generated/com/example/capstone/domain/help/entity/Qhelp.java
  back/src/main/generated/com/example/capstone/domain/qna/entity/QAnswer.java
  back/src/main/generated/com/example/capstone/domain/qna/entity/QQuestion.java
  back/src/main/java/com/example/capstone/domain/help/controller/HelpController.java
  back/src/main/java/com/example/capstone/domain/help/dto/HelpListRequest.java
  back/src/main/java/com/example/capstone/domain/help/dto/HelpListResponse.java
  back/src/main/java/com/example/capstone/domain/help/dto/HelpPostRequest.java
  back/src/main/java/com/example/capstone/domain/help/dto/HelpResponse.java
  back/src/main/java/com/example/capstone/domain/help/entity/Help.java
  back/src/main/java/com/example/capstone/domain/help/repository/HelpListRepository.java
  back/src/main/java/com/example/capstone/domain/help/repository/HelpRepositoryImpl.java
  back/src/main/java/com/example/capstone/domain/help/service/HelpService.java
  back/src/main/java/com/example/capstone/domain/qna/controller/AnswerController.java
  back/src/main/java/com/example/capstone/domain/qna/controller/QuestionController.java
  back/src/main/java/com/example/capstone/domain/qna/dto/AnswerResponse.java
  back/src/main/java/com/example/capstone/domain/qna/dto/QuestionResponse.java
  back/src/main/java/com/example/capstone/domain/qna/entity/Answer.java
  back/src/main/java/com/example/capstone/domain/qna/entity/Question.java
  back/src/main/java/com/example/capstone/domain/qna/service/AnswerService.java
  back/src/main/java/com/example/capstone/domain/qna/service/QuestionService.java
  back/src/main/java/com/example/capstone/domain/user/dto/SigninRequest.java
  back/src/main/java/com/example/capstone/domain/user/repository/UserRepository.java
Labels: 🐛 bug, 🔧 refactor, 🔒 BE

#166 Refactor/be/#163 UUID Unique 제거
  back/src/main/java/com/example/capstone/domain/help/entity/Help.java
  back/src/main/java/com/example/capstone/domain/qna/entity/Answer.java
  back/src/main/java/com/example/capstone/domain/qna/entity/Question.java
Labels: 🔧 refactor, 🔒 BE

#170 refactor:#169/로그인 로직 수정
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/home/home_screen.dart
  front/capstone_front/lib/screens/signup/signup_service.dart
  front/capstone_front/lib/screens/speech_practice/speech_custom_sentence/speech_custom_sentence.dart
  front/capstone_front/lib/screens/speech_practice/speech_custom_sentence/speech_practice_card.dart
  front/capstone_front/lib/screens/speech_practice/speech_example_sentences/speech_select_sentence_screen.dart
  front/capstone_front/lib/screens/speech_practice/speech_example_sentences/speech_sentence_card.dart
  front/capstone_front/lib/services/chatbot_service.dart
  front/capstone_front/lib/services/login_service.dart
  front/capstone_front/lib/utils/white_box.dart
Labels: 🔧 refactor, 📱 FE

#172 [FE] 공지사항 검색기능 구현
  front/capstone_front/lib/screens/notice/notice_screen.dart
  front/capstone_front/lib/services/notice_service.dart
Labels: 📝 feature, 📱 FE

#174 [FE] 채팅 기능 구현
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/models/chat_init_model.dart
  front/capstone_front/lib/models/chat_model.dart
  front/capstone_front/lib/models/chat_room_model.dart
  front/capstone_front/lib/models/helper_model.dart
  front/capstone_front/lib/screens/helper/helper_board/helper_detail_screen.dart
  front/capstone_front/lib/screens/helper/helper_board/helper_writing_card.dart
  front/capstone_front/lib/screens/helper/helper_board/helper_writing_json.dart
  front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_card.dart
  front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_list_screen.dart
  front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_room.dart
  front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_screen.dart
  front/capstone_front/lib/screens/helper/helper_screen.dart
  front/capstone_front/lib/services/chat_service.dart
  front/capstone_front/lib/utils/bubble_painter2.dart
  front/capstone_front/pubspec.yaml
Labels: 📝 feature, 📱 FE

#171 Feature/be/#159 API Rate Limiter 적용
  back-gateway/build.gradle
  back-gateway/redis-server.yml
  back-gateway/src/main/java/com/gateway/backgateway/config/GatewayConfig.java
  back-gateway/src/main/java/com/gateway/backgateway/config/RedisConfig.java
  back-gateway/src/main/java/com/gateway/backgateway/config/UserIdKeyResolver.java
  back-gateway/src/main/java/com/gateway/backgateway/exception/ErrorCode.java
  back-gateway/src/main/java/com/gateway/backgateway/exception/GlobalExceptionHandler.java
  back-gateway/src/main/java/com/gateway/backgateway/exception/TooManyRequestException.java
  back-gateway/src/main/java/com/gateway/backgateway/filter/AuthorizationHeaderFilter.java
  back-gateway/src/main/java/com/gateway/backgateway/filter/RequestRateLimitFilter.java
  back-gateway/src/main/resources/application.yml
  back/src/main/java/com/example/capstone/domain/announcement/controller/AnnouncementController.java
Labels: 📝 feature, 🔒 BE, 🔨 setting

#179 refactor: #175-중국어 지원을 위한 ZH 언어설정 추가
  back/src/main/java/com/example/capstone/domain/announcement/service/AnnouncementCrawlService.java
  back/src/main/java/com/example/capstone/domain/menu/service/MenuUpdateService.java
Labels: 🔒 BE, 🔨 setting

#184 feature:#176/홈 화면 유저정보 추가
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/models/user_info_model.dart
  front/capstone_front/lib/screens/home/home_screen.dart
  front/capstone_front/lib/screens/login/login_screen.dart
  front/capstone_front/lib/services/auth_service.dart
  front/capstone_front/lib/tempCodeRunnerFile.dart
Labels: 📝 feature, 📱 FE

#181 Refactor/be/#180 게시글 작성 content-type mapping 및 S3 이미지 용량 제한
  back/src/main/java/com/example/capstone/domain/qna/service/ImageService.java
  back/src/main/java/com/example/capstone/global/config/WebConfig.java
  back/src/main/java/com/example/capstone/global/converter/OctetStreamReadMsgConverter.java
  back/src/main/java/com/example/capstone/global/error/GlobalExceptionHandler.java
  back/src/main/java/com/example/capstone/global/error/exception/ErrorCode.java
  back/src/main/resources/application.properties
Labels: 🔧 refactor, 🔒 BE, 🔨 setting

#191 [FE] qna 게시글 작성 구현 및 헬퍼, qna 작성 데이터 유저 데이터로 변경
  front/capstone_front/lib/screens/helper/helper_write_screen.dart
  front/capstone_front/lib/screens/qna/qna_write/qna_write_screen.dart
  front/capstone_front/lib/services/auth_service.dart
  front/capstone_front/lib/services/qna_service.dart
  front/capstone_front/pubspec.yaml
Labels: 📝 feature, 📱 FE

#177 Feature/ai/#149 chatbot memory
  ai/deepl_test.py
  ai/llm/__pycache__/llm_rag.cpython-312.pyc
  ai/llm/__pycache__/llm_rag.cpython-39.pyc
  ai/llm/deepl_translator.py
  ai/llm/llm_rag.py
  ai/llm/prompt.py
  ai/run_chatbot.py
  ai/vectordb/__pycache__/vector_db.cpython-39.pyc
Labels: 📱 FE, 👽️AI

#192 feat: #109-채팅 미리보기 버그 수정
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/models/chat_room_model.dart
  front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_card.dart
  front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_list_screen.dart
  front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_room.dart
  front/capstone_front/lib/screens/qna/qna_write/qna_write_screen.dart
  front/capstone_front/lib/services/chat_service.dart
Labels: 🐛 bug, 📝 feature, 📱 FE

#200 Refactor/fe/#198 design refactor
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/login/login_screen.dart
  front/capstone_front/lib/screens/notice/notice_screen.dart
  front/capstone_front/lib/screens/qna/qna_list_screen/qna_list_screen.dart
  front/capstone_front/lib/screens/question/question_screen.dart
  front/capstone_front/lib/utils/search_screen.dart
Labels: 🔧 refactor, 📱 FE

#199 Feature/be/#130 추천한 댓글 여부 및 Redis를 사용한 Race condition 해결
  back-gateway/src/main/java/com/gateway/backgateway/config/GatewayConfig.java
  back/src/main/generated/com/example/capstone/domain/like/entity/QLike.java
  back/src/main/java/com/example/capstone/domain/help/controller/HelpController.java
  back/src/main/java/com/example/capstone/domain/help/exception/HelpNotFoundException.java
  back/src/main/java/com/example/capstone/domain/help/service/HelpService.java
  back/src/main/java/com/example/capstone/domain/like/entity/Like.java
  back/src/main/java/com/example/capstone/domain/like/repository/LikeCustomRepository.java
  back/src/main/java/com/example/capstone/domain/like/repository/LikeRepository.java
  back/src/main/java/com/example/capstone/domain/like/repository/LikeRepositoryImpl.java
  back/src/main/java/com/example/capstone/domain/like/service/LikeService.java
  back/src/main/java/com/example/capstone/domain/menu/controller/MenuController.java
  back/src/main/java/com/example/capstone/domain/menu/service/MenuCrawlingService.java
  back/src/main/java/com/example/capstone/domain/menu/service/MenuUpdateService.java
  back/src/main/java/com/example/capstone/domain/qna/controller/AnswerController.java
  back/src/main/java/com/example/capstone/domain/qna/controller/FAQController.java
  back/src/main/java/com/example/capstone/domain/qna/controller/QuestionController.java
  back/src/main/java/com/example/capstone/domain/qna/dto/AnswerListResponse.java
  back/src/main/java/com/example/capstone/domain/qna/entity/Answer.java
  back/src/main/java/com/example/capstone/domain/qna/entity/FAQImage.java
  back/src/main/java/com/example/capstone/domain/qna/entity/QuestionImage.java
  back/src/main/java/com/example/capstone/domain/qna/exception/AnswerNotFoundException.java
  back/src/main/java/com/example/capstone/domain/qna/exception/FAQNotFoundException.java
  back/src/main/java/com/example/capstone/domain/qna/exception/QuestionNotFoundException.java
  back/src/main/java/com/example/capstone/domain/qna/repository/AnswerListRepository.java
  back/src/main/java/com/example/capstone/domain/qna/repository/AnswerRepositoryImpl.java
  back/src/main/java/com/example/capstone/domain/qna/repository/QuestionRepositoryImpl.java
  back/src/main/java/com/example/capstone/domain/qna/service/AnswerService.java
  back/src/main/java/com/example/capstone/domain/qna/service/FAQService.java
  back/src/main/java/com/example/capstone/domain/qna/service/ImageService.java
  back/src/main/java/com/example/capstone/domain/qna/service/QuestionService.java
  back/src/main/java/com/example/capstone/domain/speech/controller/SpeechController.java
  back/src/main/java/com/example/capstone/domain/speech/dto/SpeechRequest.java
  back/src/main/java/com/example/capstone/global/config/RedisConfig.java
Labels: 📝 feature, 🔧 refactor, 🔒 BE

#203 refactor: 메뉴 크롤링 작업 수정
  back/src/main/java/com/example/capstone/domain/menu/controller/MenuController.java
  back/src/main/java/com/example/capstone/domain/menu/service/MenuUpdateService.java
Labels: 🔧 refactor, 🔒 BE

#205 bug: #204-헬퍼화면에서 헬피글쓰면 헬퍼화면에서 보이는 버그 수정
  front/capstone_front/lib/screens/helper/helper_board/helper_board_screen.dart
Labels: 🐛 bug, 📱 FE

#207 Feature/fe/#185 school info
  front/capstone_front/assets/images/facility_time_en.jpg
  front/capstone_front/assets/images/facility_time_ko.jpg
  front/capstone_front/assets/images/facility_time_zh.jpg
  front/capstone_front/lib/screens/home/home_screen.dart
  front/capstone_front/pubspec.yaml
Labels: 📝 feature, 📱 FE

#208 Bug/fe/#197 fix bug
  front/capstone_front/lib/screens/helper/helper_board/helper_detail_screen.dart
  front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_card.dart
  front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_list_screen.dart
Labels: 🐛 bug, 📝 feature, 📱 FE

#211 Feature/fe/#209 helper my article
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/assets/translations/zh-CN.json
  front/capstone_front/lib/screens/chatbot/chatbot_screen.dart
  front/capstone_front/lib/screens/helper/helper_board/helper_board_screen.dart
  front/capstone_front/lib/screens/helper/helper_board/helper_detail_screen.dart
  front/capstone_front/lib/screens/helper/helper_board/helper_writing_card.dart
  front/capstone_front/lib/services/helper_service.dart
Labels: 📝 feature, 📱 FE

#213 Feature/be/#159 api rate limiter
  back-gateway/src/main/java/com/gateway/backgateway/config/GatewayConfig.java
  back-gateway/src/main/java/com/gateway/backgateway/filter/AuthorizationHeaderFilter.java
  back-gateway/src/main/java/com/gateway/backgateway/filter/RequestRateLimitFilter.java
  back-gateway/src/main/resources/application.yml
  back/.gitignore
  back/src/main/generated/com/example/capstone/domain/user/entity/QUser.java
  back/src/main/java/com/example/capstone/domain/auth/controller/AuthController.java
  back/src/main/java/com/example/capstone/domain/auth/dto/ReissueRequest.java
  back/src/main/java/com/example/capstone/domain/auth/service/AuthService.java
  back/src/main/java/com/example/capstone/domain/jwt/JwtTokenProvider.java
  back/src/main/java/com/example/capstone/domain/user/dto/SignupRequest.java
  back/src/main/java/com/example/capstone/domain/user/dto/UserProfileUpdateRequest.java
  back/src/main/java/com/example/capstone/domain/user/entity/User.java
Labels: 📝 feature, 💩 chore, 🔒 BE

#217 Feature/be/#130 추천시 request body 요청 수정 + 추천 여부 null 반환 수정
  back/src/main/java/com/example/capstone/domain/qna/controller/AnswerController.java
  back/src/main/java/com/example/capstone/domain/qna/dto/LikeRequest.java
  back/src/main/java/com/example/capstone/domain/qna/repository/AnswerRepositoryImpl.java
Labels: 🐛 bug, 🔧 refactor, 🔒 BE

#218 Feature/ai/#202 app data
  ai/.gitignore
  ai/crawler/pdf_reader.py
  ai/database.py
  ai/models.py
  ai/server.py
Labels: 📝 feature, 👽️AI

#225 Feature/be/#216 timer aop
  back/build.gradle
  back/src/main/generated/com/example/capstone/domain/announcement/mapper/AnnouncementMapperImpl.java
  back/src/main/generated/com/example/capstone/domain/user/util/UserMapperImpl.java
  back/src/main/java/com/example/capstone/domain/announcement/controller/AnnouncementController.java
  back/src/main/java/com/example/capstone/domain/announcement/dto/AnnouncementSearchListRequest.java
  back/src/main/java/com/example/capstone/domain/announcement/entity/AnnouncementFile.java
  back/src/main/java/com/example/capstone/domain/announcement/repository/AnnouncementRepositoryImpl.java
  back/src/main/java/com/example/capstone/domain/help/controller/HelpController.java
  back/src/main/java/com/example/capstone/domain/menu/controller/MenuController.java
  back/src/main/java/com/example/capstone/domain/qna/controller/AnswerController.java
  back/src/main/java/com/example/capstone/domain/qna/controller/FAQController.java
  back/src/main/java/com/example/capstone/domain/qna/controller/QuestionController.java
  back/src/main/java/com/example/capstone/domain/speech/controller/SpeechController.java
  back/src/main/java/com/example/capstone/domain/user/controller/UserController.java
  back/src/main/java/com/example/capstone/global/aop/TimerAop.java
  back/src/main/java/com/example/capstone/global/util/Timer.java
Labels: 📝 feature, 💩 chore, 🔒 BE

#223 Feature/ai/#220 apago translate
  ai/llm/llm_rag.py
  ai/llm/papago.py
  ai/run_chatbot.py
Labels: 🔧 refactor, 👽️AI

#224 Feature/fe/#221 translate static word
  front/capstone_front/assets/translations/en-US.json
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/assets/translations/zh-CN.json
  front/capstone_front/lib/screens/cafeteriaMenu/cafeteriaMenuScreen.dart
  front/capstone_front/lib/screens/faq/faq_screen.dart
  front/capstone_front/lib/screens/faq/test_faq_data.dart
  front/capstone_front/lib/screens/helper/helper_chatting/helper_chatting_room.dart
  front/capstone_front/lib/screens/home/home_screen.dart
  front/capstone_front/lib/screens/notice/notice_detail_screen.dart
  front/capstone_front/lib/screens/notice/notice_screen.dart
  front/capstone_front/lib/screens/notice/test_notice_data.dart
  front/capstone_front/lib/screens/qna/qna_detail/qna_detail_screen.dart
  front/capstone_front/lib/screens/qna/qna_list_screen/qna_list_screen.dart
  front/capstone_front/lib/screens/qna/qna_write/qna_write_screen.dart
  front/capstone_front/lib/screens/question/question_screen.dart
  front/capstone_front/lib/screens/speech_practice/speech_custom_sentence/speech_custom_sentence.dart
  front/capstone_front/lib/screens/speech_practice/speech_example_sentences/speech_sentence_card.dart
  front/capstone_front/lib/screens/speech_practice/speech_practice_screen.dart
  front/capstone_front/lib/services/auth_service.dart
  front/capstone_front/lib/services/chatbot_service.dart
Labels: 🐛 bug, 📝 feature, 💩 chore, 📱 FE

#233 feat: #232-cloud front 캐싱 주소저장 변경
  .github/workflows/deploy.yml
  back/.env.example
  back/src/main/java/com/example/capstone/domain/qna/service/ImageService.java
  back/src/main/resources/application.properties
Labels: 🔧 refactor, 🔒 BE, 🔨 setting

#234 fix: Gradlew 개행 문제 해결
  back-gateway/src/main/java/com/gateway/backgateway/filter/GlobalLoggingFilter.java
  back/nginx/test.conf.template
Labels: 💩 chore, 🔒 BE

#235 fix : GET 로깅 제외
  back-gateway/src/main/java/com/gateway/backgateway/filter/GlobalLoggingFilter.java
  docker-compose.yml
Labels: 💩 chore, 🔒 BE

#236 Develop back README.md
  .github/workflows/deploy.yml
  back-gateway/src/main/java/com/gateway/backgateway/filter/AuthorizationHeaderFilter.java
  back-gateway/src/main/java/com/gateway/backgateway/filter/GlobalLoggingFilter.java
  back-gateway/src/main/resources/application.yml
  back/.env.example
  back/README.md
  back/docker-compose.yml
  back/env.sh
  back/nginx/test.conf.template
  back/nginx/tool/encrypt.sh
  back/src/main/java/com/example/capstone/domain/announcement/controller/AnnouncementController.java
  back/src/main/java/com/example/capstone/domain/announcement/service/AnnouncementCallerService.java
  back/src/main/java/com/example/capstone/domain/announcement/service/AnnouncementCrawlService.java
  back/src/main/java/com/example/capstone/domain/qna/service/ImageService.java
  back/src/main/java/com/example/capstone/global/config/AsyncConfig.java
  back/src/main/resources/application.properties
  docker-compose.yml
Labels: 💩 chore, 🔒 BE
