Repository kookmin-sw/capstone-2024-30, pull requests merged in 2024-03, with the labels that each got.

#21 Ocr for crawling kmu notice
  ai/.gitignore
  ai/crawler/__pycache__/notice_clawler.cpython-39.pyc
  ai/crawler/clawler_utils.py
  ai/crawler/clova_ocr.py
  ai/crawler/main.py
  ai/crawler/notice_clawler.py
  ai/crawler/test_by_sampling.py
  ai/requirements.txt
Labels: 📝 feature, 👽️AI

#25 Feature/fe/#24 save login info
  front/capstone_front/.gitignore
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/login/login_screen.dart
Labels: 📝 feature, 📱 FE

#28 feature: #26/리스트뷰 추가
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/home_screen.dart
  front/capstone_front/lib/screens/speeking_practice/speeking_practice_screen.dart
Labels: 📝 feature, 📱 FE

#29 bug: #27-회원가입 완료 시 메인페이지로 이동하는 버그 수정
  front/capstone_front/lib/screens/login/signup_screen.dart
Labels: 🐛 bug, 📱 FE

#31 feature: #26/녹음과 재생 기능 구현
  front/capstone_front/android/app/src/main/AndroidManifest.xml
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/home_screen.dart
  front/capstone_front/lib/screens/speeking_practice/pronunciation_practice_screen.dart
  front/capstone_front/lib/screens/speeking_practice/pronunciation_senctence_screen.dart
  front/capstone_front/lib/screens/speeking_practice/speeking_practice_screen.dart
  front/capstone_front/lib/screens/speeking_practice/utils/simple_recorder.dart
  front/capstone_front/lib/test.dart
  front/capstone_front/lib/utils/page_animation.dart
  front/capstone_front/pubspec.yaml
Labels: 📝 feature, 📱 FE

#33 fix: #32/ios 마이크로폰 권한추가
  front/capstone_front/ios/Podfile
  front/capstone_front/ios/Runner.xcodeproj/project.pbxproj
  front/capstone_front/ios/Runner/Info.plist
Labels: 🐛 bug, 📱 FE

#34 feature: #15/학식정보 스크린 생성
  front/capstone_front/assets/translations/en-US.json
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/cafeteriaMenu/cafeteriaMenuScreen.dart
  front/capstone_front/lib/screens/cafeteriaMenu/dateChanger.dart
  front/capstone_front/lib/screens/cafeteriaMenu/menuCard.dart
  front/capstone_front/lib/screens/home_screen.dart
Labels: 📝 feature, 📱 FE

#35 feature: #22/회원가입 및 JWT AccessToken 발급 + #10/프로젝트 Global 설정
  back/.env.example
  back/build.gradle
  back/src/main/java/com/example/capstone/domain/auth/controller/AuthController.java
  back/src/main/java/com/example/capstone/domain/auth/dto/SigninRequest.java
  back/src/main/java/com/example/capstone/domain/auth/dto/SigninResponse.java
  back/src/main/java/com/example/capstone/domain/auth/dto/SignupRequest.java
  back/src/main/java/com/example/capstone/domain/auth/exception/AlreadyEmailExistException.java
  back/src/main/java/com/example/capstone/domain/auth/service/LoginService.java
  back/src/main/java/com/example/capstone/domain/jwt/JwtAuthenticationFilter.java
  back/src/main/java/com/example/capstone/domain/jwt/JwtClaim.java
  back/src/main/java/com/example/capstone/domain/jwt/JwtToeknProvider.java
  back/src/main/java/com/example/capstone/domain/jwt/JwtTokenProvider.java
  back/src/main/java/com/example/capstone/domain/jwt/PrincipalDetails.java
  back/src/main/java/com/example/capstone/domain/jwt/exception/JwtTokenInvalidException.java
  back/src/main/java/com/example/capstone/domain/user/entity/User.java
  back/src/main/java/com/example/capstone/domain/user/repository/UserRepository.java
  back/src/main/java/com/example/capstone/domain/user/util/UserMapper.java
  back/src/main/java/com/example/capstone/global/config/SecurityConfig.java
  back/src/main/java/com/example/capstone/global/config/SwaggerConfig.java
  back/src/main/java/com/example/capstone/global/error/ErrorResponse.java
  back/src/main/java/com/example/capstone/global/error/GlobalExceptionHandler.java
  back/src/main/java/com/example/capstone/global/error/JwtAccessDeniedHandler.java
  back/src/main/java/com/example/capstone/global/error/JwtAuthenticationEntryPoint.java
  back/src/main/java/com/example/capstone/global/error/exception/BusinessException.java
  back/src/main/java/com/example/capstone/global/error/exception/EntityNotFoundException.java
  back/src/main/java/com/example/capstone/global/error/exception/ErrorCode.java
  back/src/main/java/com/example/capstone/global/error/exception/InvalidValueException.java
  back/src/main/resources/application.properties
  front/capstone_front/.gitignore
  front/capstone_front/android/app/build.gradle
  front/capstone_front/assets/translations/en-US.json
  front/capstone_front/assets/translations/ko-KR.json
  front/capstone_front/ios/Flutter/Debug.xcconfig
  front/capstone_front/ios/Flutter/Release.xcconfig
  front/capstone_front/ios/Podfile
  front/capstone_front/ios/Runner.xcodeproj/project.pbxproj
  front/capstone_front/ios/Runner.xcworkspace/contents.xcworkspacedata
  front/capstone_front/ios/Runner/GoogleService-Info.plist
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/home_screen.dart
  front/capstone_front/lib/screens/login/assets/college_department.dart
  front/capstone_front/lib/screens/login/login_screen.dart
  front/capstone_front/lib/screens/login/signup_screen.dart
  front/capstone_front/macos/Flutter/Flutter-Debug.xcconfig
  front/capstone_front/macos/Flutter/Flutter-Release.xcconfig
  front/capstone_front/macos/Podfile
  front/capstone_front/macos/Runner/GoogleService-Info.plist
  front/capstone_front/macos/firebase_app_id_file.json
  front/capstone_front/pubspec.yaml
Labels: 📝 feature, 🔒 BE, 🔨 setting

#37 feature/fe/#26-녹음 및 평가 UI 제작
  front/capstone_front/assets/translations/en-US.json
  front/capstone_front/lib/main.dart
  front/capstone_front/lib/screens/home_screen.dart
  front/capstone_front/lib/screens/speeking_practice/pronunciation_practice_screen.dart
  front/capstone_front/lib/screens/speeking_practice/pronunciation_select_sentence_screen.dart
  front/capstone_front/lib/screens/speeking_practice/pronunciation_senctence_screen.dart
  front/capstone_front/lib/screens/speeking_practice/pronunciation_sentence_card.dart
  front/capstone_front/lib/screens/speeking_practice/utils/example_sentences.dart
  front/capstone_front/lib/screens/speeking_practice/utils/simple_recorder.dart
  front/capstone_front/lib/utils/page_animation.dart
Labels: 📝 feature, 📱 FE
